#!/bin/bash

#SBATCH -J test
#SBATCH -t 720:00:00
#SBATCH -n 12
#SBATCH -N 1 
#SBATCH -p astra
#SBATCH -o %x.o%j
#SBATCH -e %x.e%j
##SBATCH -w c0055
##SBATCH -x c0055 
##SBATCH --exclusive

# Enter the working directory
cd ${SLURM_SUBMIT_DIR}

echo "starting $SLURM_JOB_ID at `date` on `hostname`"

# Activate the Conda virtual environment
source ~/.bashrc 

# Make a temp directory
MYTMP=/tmp/${SLURM_JOB_ID}
/usr/bin/mkdir -p $MYTMP

#mpiexec -pernode scp -v ${SLURM_SUBMIT_DIR}/restart.out  $MYTMP/. 
mpiexec -pernode scp -v ${SLURM_SUBMIT_DIR}/input_gamess.py  $MYTMP/. 
mpiexec -pernode scp -v ${SLURM_SUBMIT_DIR}/input_simulation.py  $MYTMP/. 
mpiexec -pernode scp -v ${SLURM_SUBMIT_DIR}/geo_gamess  $MYTMP/. 
mpiexec -pernode scp -v ${SLURM_SUBMIT_DIR}/vec_gamess  $MYTMP/. 
mpiexec -pernode scp -v ${SLURM_SUBMIT_DIR}/hess_gamess  $MYTMP/. 
mpiexec -pernode scp -v ${SLURM_SUBMIT_DIR}/mass_gamess  $MYTMP/. 
mpiexec -pernode scp -v ${SLURM_SUBMIT_DIR}/rungms-pool  $MYTMP/. 
mpiexec -pernode scp -v ${SLURM_SUBMIT_DIR}/runG_common_pool  $MYTMP/. 
mpiexec -pernode scp -v ~/PySCES-main/pysces/main.py  $MYTMP/. 
mpiexec -pernode scp -v ~/PySCES-main/pysces/subroutines.py  $MYTMP/. 
mpiexec -pernode scp -v ~/PySCES-main/pysces/fileIO.py  $MYTMP/.

cd $MYTMP

### set up python environment ###
module load python/3.10.13
#creating a virtual environment
python3.10 -m venv env
source env/bin/activate

pip install --upgrade pip
pip install numpy pandas scipy 
#pip list modules

### run python ###
time python3.10 main.py

deactivate
rm -r env

# Copy output files back from the temp directory to working directory
rsync -r $MYTMP/ $SLURM_SUBMIT_DIR/outputs/

rm -rf $MYTMP

exit 0 


 
